USE sales_performance_project;


#1. The sales manager wants to see the total sales amount generated by each salesperson.
# Return the salesperson's name and total sales, sorted from highest to lowest.

WITH total_sales_cte AS
(
  SELECT DISTINCT salesperson,SUM(amount) OVER(PARTITION BY salesperson) AS total_sales
  FROM sales
  
)
 SELECT *
FROM total_sales_cte
ORDER BY total_sales DESC;


#2. Rank the salespeople based on their total sales amount, with the highest total sales receiving rank 1.

WITH sales_ranking AS
(
 SELECT DISTINCT salesperson,SUM(amount) OVER(PARTITION BY salesperson) AS total_sales
 FROM sales
 )

SELECT *,RANK()OVER(ORDER BY total_sales DESC) ranking
FROM sales_ranking;


#3. The manager wants to identify the top 3 salespeople based on total sales. Return their names, total sales and rank.

WITH total_sales AS
(
 SELECT DISTINCT salesperson,SUM(amount) OVER(PARTITION BY salesperson) AS total_sales
 FROM sales
 )
, sales_rank AS
(
SELECT *,DENSE_RANK()OVER(ORDER BY total_sales DESC) ranking
FROM total_sales
)

SELECT*
FROM sales_rank
HAVING ranking <= 3;


#4. Calculate the total quantity of products sold by each salesperson and rank them based on total quantity sold.

WITH quantity_ranking AS (
SELECT  DISTINCT salesperson,SUM(quantity)OVER(PARTITION BY salesperson) AS total_quantity
FROM sales 
)
SELECT*,RANK()OVER(ORDER BY total_quantity DESC) AS quantity_rank
FROM quantity_ranking;

#5. The manager wants to see each salesperson's average sale amount.
# Return the salesperson and their average sale amount, from highest to lowest

   SELECT  DISTINCT salesperson,AVG(amount)OVER(PARTITION BY salesperson) AS  average_sale_amount
   FROM sales
   ORDER BY average_sale_amount DESC;
   

#6. Rank the salespeople based on their average sale amount.

WITH sale_average AS
(
SELECT DISTINCT salesperson,AVG(amount)OVER(PARTITION BY salesperson) AS average_sale_amnt
FROM sales
)
SELECT *,RANK()OVER(ORDER BY average_sale_amnt DESC) ranking
FROM sale_average;

#7. The company wants to compare salespeople within each product category. 
#   Calculate each salesperson's total sales for each category and rank them within that category.

WITH category_total_sales AS (
SELECT DISTINCT salesperson,category,SUM(amount)OVER(PARTITION BY  salesperson ,category )  AS totaL_sales
FROM sales
)
SELECT*,RANK()OVER(PARTITION BY category ORDER BY totaL_sales  DESC) AS ranking
FROM   category_total_sales;


#8. Identify the highest-selling salesperson for each product category. Return the category, salesperson and total sales.

WITH category_sales AS
(
SELECT DISTINCT category,salesperson,SUM(amount)OVER(PARTITION BY salesperson,category) AS total_sales
FROM sales
)
,highest_selling AS(
SELECT*,MAX(total_sales)OVER(PARTITION BY category) AS highest_total_sales
FROM category_sales
)
SELECT category,salesperson,total_sales,highest_total_sales
FROM highest_selling
HAVING highest_total_sales = total_sales;





#9. The manager wants to see each salesperson's total sales and their percentage contribution to the company's overall sales.

WITH salesperson_sales AS
(
SELECT DISTINCT salesperson,SUM(amount)OVER(PARTITION BY salesperson) AS total_sales
FROM sales
),
overall_total_sale AS 
(
 SELECT SUM(total_sales) AS overall_sales
 FROM salesperson_sales
)
,getPercentage as
(
 SELECT *,(SELECT  overall_sales
			FROM  overall_total_sale) AS overall_sales
 FROM salesperson_sales
)
SELECT salesperson,total_sales,
CONCAT(FORMAT(((total_sales/overall_sales)*100),1),'%' )AS percentage_contribution
FROM getPercentage
;


#10. Identify the salesperson who generated the highest total sales in each month.

#GET MONTH
WITH getYearMonth AS 
(
SELECT salesperson,amount,SUBSTRING(sale_date,6,2) AS months
FROM sales
),
#GET TOTAL SALES AMOUNT OF EACH SALES PERSON FOR EACH MONTH
getTotalSales AS
(
SELECT *,SUM(amount)OVER(PARTITION BY salesperson,months) AS total_sales
FROM getYearMonth
)
#GET THE HIGHEST TOTAL SALE OF THE MONTH
, getMonthTotalSales AS
(
 SELECT *,MAX(total_sales)OVER(PARTITION BY months) AS highest_total 
 FROM getTotalSales

)

SELECT DISTINCT salesperson,total_sales,months
FROM getMonthTotalSales
WHERE total_sales = highest_total;